# Aquest és el teu script complert i corregit

name: Build & Deploy EnergyPlus MCP Server

on:
  push:
    branches:
      - main

env:
  # !!! IMPORTANT: Adapta el nom de la imatge al teu registre i grup
  IMAGE_TAG: registry.wattega.com/el-teu-grup/energyplus-mcp-server:latest
  # !!! IMPORTANT: Aquest ha de ser el nom del teu 'Deployment' a Kubernetes
  APP_NAME: energyplus-server 

jobs:
  build-and-deploy:
    name: Build and Deploy to K3s
    # Executem tot en un sol 'job' per simplicitat
    runs-on: [self-hosted]
    steps:
      - name: Checkout del codi
        uses: actions/checkout@v4

      - name: Login to private registry (registry.wattega.com)
        uses: docker/login-action@v3
        with:
          registry: registry.wattega.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Assegurem que utilitza el Dockerfile correcte d'aquest projecte
          file: .devcontainer/Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}
      
      - name: Deploy to K3s by restarting the deployment
        run: |
          # Aquesta comanda força a Kubernetes a descarregar la nova imatge amb la tag ':latest'
          kubectl rollout restart deployment/${{ env.APP_NAME }}